### ISSUE TITLE
Please move the license at the top of the README to a LICENSE file

### ISSUE THREAD

**Issue by mbrukman** [NVIDIA/ngpt#2]
First of all, thank you for sharing this project with us!

The [`README.md`](https://github.com/NVIDIA/ngpt/blob/86cc59470bcc4a1f9afceea34de9cb2396fc0dbb/README.md?plain=1#L1-L22) includes the MIT license at the top of the file in full:

https://github.com/NVIDIA/ngpt/blob/86cc59470bcc4a1f9afceea34de9cb2396fc0dbb/README.md?plain=1#L1-L22

It would be more effective if this license text were moved from the `README.md` to a (new) `LICENSE` file as then GitHub would automatically add a badge to the repo labeling it as an MIT-licensed repo, as you can see in this blog post:

https://github.blog/news-insights/product-news/license-now-displayed-on-repository-overview/

It would also clean up the README and make it more readable. You can still add a section at the end to highlight the license and point to the `LICENSE` file if you'd like.

Just a thought. Hope this helps.

**Comment by iloshchilov** [comment]
Thank you very much for this suggestion! We have added the licence file to be tracked by github. However, we still should keep the licence text in readme because we were told to do it this way.
